name: Rolling Release

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    name: Build & Push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jgroups: [3.6.20, 4.2.4, 5.0.0]
        java: [8, 11]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push JDK
        uses: docker/build-push-action@v2
        with:
          context: .
          file: "./Dockerfile"
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            JAVA_VERSION=${{ matrix.java }}
            JGROUPS_VERSION=${{ matrix.jgroups }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/jgroups:${{ matrix.java }}-${{ matrix.jgroups }}
          no-cache: false
          labels: |
            org.opencontainers.image.title=jgroups
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
      - name: Build and Push JRE
        uses: docker/build-push-action@v2
        with:
          context: .
          file: "./Dockerfile.jre"
          platforms: linux/amd64,linux/arm64/v8
          push: true
          build-args: |
            JAVA_VERSION=${{ matrix.java }}
            JGROUPS_VERSION=${{ matrix.jgroups }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/jgroups:jre-${{ matrix.java }}-${{ matrix.jgroups }}
          no-cache: false
          labels: |
            org.opencontainers.image.title=jgroups
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
